import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    container:{
        padding:7,
        height:'95%',
        width:'100%',
    },
    NomPersona:{
        flexDirection:'row'
    },
    conatinerimage:{
        height:'15%',
        width:'35%',
    },
    image:{
        justifyContent:'center',
        width:'57%',
        height: 80,
    },
    nombrePersona:{
        color:'black',
        fontSize: 18,
    },
    limite:{
        flexDirection:'row',
        paddingTop:2,
    },
    numero:{
        fontSize:18,
        color:'#2B78E4',
        paddingLeft:10,
    }, 
    vence:{
        flexDirection:'row',
        paddingTop:2,
    },
    PuntosAcu:{
        fontSize:18,
        color:'#CF2A27',
        paddingLeft:10,
    },
    txtvence:{
        fontSize:18,
        color:'black',

    },
    compra:{
        fontSize:18,
        color:'#2B78E4',
        paddingLeft:15,
    },

    total:{
        fontSize:18,
        color:'#2B78E4',
        textAlign:'center',
        paddingTop:2,
    },
    ListCompras:{
        padding:2,
        width:'100%',
        height:'68.5%'
    }, 
    txtfinal:{
        flexDirection:'row',
    },
    txtpreciofinal:{
        fontSize:18,
        color:'black',
        textAlign:'center',
        paddingTop:2,
        paddingRight:20,
    },
    finaltxt:{
        fontSize:18,
        color:'#2B78E4',
        textAlign:'center',
        paddingTop:2,
        paddingRight:20,
    },
});