import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    container:{
        padding:7,
        height:'95%',
        width:'100%',
    },
    NomPersona:{
        flexDirection:'row'
    },
    conatinerimage:{
        height:'15%',
        width:'35%',
    },
    image:{
        justifyContent:'center',
        width:'57%',
        height: 80,
    },
    nombrePersona:{
        color:'black',
        fontSize: 18,
    },
    limite:{
        flexDirection:'row',
        paddingTop:2,
    },
    numero:{
        fontSize:18,
        color:'#2B78E4',
        paddingLeft:10,
    }, 
    vence:{
        flexDirection:'row',
        paddingTop:2,
    },
    PuntosAcu:{
        fontSize:18,
        color:'#2B78E4',
        paddingLeft:10,
    },
    txtvence:{
        fontSize:18,
        color:'black',

    },
    compra:{
        fontSize:18,
        color:'#2B78E4',
        paddingLeft:15,
    },
    ContainerLimite:{
        flexDirection:'row-reverse',
    },
    txtLimite:{
        fontSize:18,
        color:'#2B78E4',
        paddingLeft:20,
    },
    txtCredito:{
        fontSize:18,
        color:'red',
    },
    txtcre:{
        fontSize:18,
        color:'black',
    },
    total:{
        fontSize:18,
        color:'#2B78E4',
        textAlign:'center',
        paddingTop:2,
    },
    ListCompras:{
        padding:2,
        width:'100%',
        height:'50%'
    }, 
    txtfinal:{
        flexDirection:'row',
    },
    txtpreciofinal:{
        fontSize:18,
        color:'#2B78E4',
        textAlign:'center',
        paddingTop:5,
        paddingRight:10,
    },
    finaltxt:{
        fontSize:18,
        color:'black',
        textAlign:'center',
        paddingTop:5,
        paddingRight:10,
    },
    containerbtn:{
        height:'6%',
        width:'100%',
        paddingLeft:17,
    },
    btn:{
        backgroundColor:'#2B78E4',
        height:'100%',
        width:'90%',
        borderRadius:10,
        justifyContent:'center',
    },
    btntxt:{
        color:'#fff',
        fontSize:20,
        textAlign:'center',
    },
});